use learn;
CREATE TABLE IF NOT EXISTS `TBL_PAY_MENT` (
    `ID` BIGINT(20) NOT NUll AUTO_INCREMENT COMMENT 'ID',
    `serial` VARCHAR(255) DEFAULT NULL COMMENT '流水号',
    PRIMARY KEY(`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8
