server:
  port: 801
  servlet:
    context-path: /order
spring:
  application:
    name: openfeign-order-service

eureka:
  client:
    # 不注册至eureka，此处只做服务调用
    register-with-eureka: false
    # 拉取eureka中的服务
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eurekaServer.com:7001/eureka, http://eurekaServerSlave.com:7001/eureka
