server:
  port: 8004

spring:
  application:
    name: zk-payment-service

  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.18.164:3306/learn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: admin

  cloud:
    zookeeper:
      # 指定zookeeper服务的地址，集群使用逗号分隔
      # 注册成功后，可以使用zkCli.sh脚本，通过 ls /services 命令查看已注册的服务
      connect-string: 192.168.18.161:2181, 192.168.18.162:2181, 192.168.18.163:2181
