server:
  port: 80
  servlet:
    context-path: /order
spring:
  application:
    name: order-service

eureka:
  client:
    # 注册至eureka
    register-with-eureka: true
    # 拉取eureka中的服务
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eurekaServer.com:7001/eureka, http://eurekaServerSlave.com:7001/eureka
