server:
  port: 9527
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能, 利用微服务名进行路由
          # 通过ip:port/微服务名/url发送请求, 如http://localhost:9527/PAYMENT-SERVICE/payment/query/1
          enabled: true
      routes:
        - id: route-1   # 路由的ID, 没有固定规则但要求唯一, 建议配合服务名
          #uri: http://localhost:8001  #服务的地址
          uri: lb://PAYMENT-SERVICE # 启用动态路由后, 提供服务的地址, lb表示loadbalance
          predicates:
            - Path=/payment/query/**  # 断言, 路径相匹配的路由
            - Path=/payment/addPayment/**
          #filters:
eureka:
  client:
    # true 表示将自己注册到eurekaServer
    register-with-eureka: true
    # true 表示从eurekaServer拉取服务，默认为true，单节点无所谓，集群必须设置为true才能配置ribbon使用，实现负载均衡
    fetch-registry: true
    service-url:
      # eureka服务默认地址
      #defaultZone: http://localhost:7001/eureka
      # 将服务注册到eureka集群中
      defaultZone: http://eurekaServer.com:7001/eureka, http://eurekaServerSlave.com:7002/eureka
  instance:
    # instance-id 指定注册到eureka的服务名称
    instance-id: gateway-service-9527
    # 访问路径可以显示IP地址
    prefer-ip-address: true

