server:
  port: 81
  servlet:
    context-path: /order
spring:
  application:
    name: zk-order-service
  cloud:
    zookeeper:
      connect-string: 192.168.18.161:2181, 192.168.18.162:2181, 192.168.18.163:2181
      discovery:
        instance-id: order-service-81
        instance-port: 81
