server:
  port: 7002
eureka:
  instance:
    hostname: eurekaServerSlave.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # 需要配合修改主机的hosts文件, 添加主机映射

      # 配置eureka集群: 有7001和7002两个eureka服务
      # 1. 修改eureka.instance.hostname，如修改为eurekaServerSlave.com
      # 2. 修改主机hosts文件，添加主机映射  127.0.0.1 eurekaServer.com  127.0.0.1 eurekaServerSlave.com
      # 3. 修改yml文件，互相注册，eurekaServer注册到eurekaServerSlave上，eurekaServerSlave注册到eurekaServer上
      # defaultZone: http://eurekaServer.com:7001/eureka   defaultZone: http://eurekaServerSlave.com:7001/eureka
      defaultZone: http://eurekaServer.com:7001/eureka
  server:
    # eureka的自我保护配置，关闭后，不可用服务会被立即剔除
    enable-self-preservation: false
    # eureka中注册的服务的驱逐间隔
    eviction-interval-timer-in-ms: 2000
